---
development:
  cloud_name: www-jabitz-com
  api_key: '617632437929693'
  api_secret: yb70EVTDFC8rPsrcgl7lCFcVZ9w
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: www-jabitz-com
  api_key: '617632437929693'
  api_secret: yb70EVTDFC8rPsrcgl7lCFcVZ9w
  enhance_image_tag: true
  static_image_support: true
staging:
  cloud_name: www-jabitz-com
  api_key: '617632437929693'
  api_secret: yb70EVTDFC8rPsrcgl7lCFcVZ9w
  enhance_image_tag: true
  static_image_support: false
